
const CHART_FURCATION_SYMBOL_FONT = "22px serif";
const CHART_FURCATION_TRIANGLE_COLOR = "#FF0000";
const CHART_FURCATION_TRIANGLE_LINE_WIDTH = 2;
const CHART_TOOTH_NO_FONT = "18px serif";

const CHART_PD_SHOW_MIN_VALUE = 4;
const CHART_PD_LINE_WIDTH = 7;
const CHART_PD_LINE_COLOR = "#FF0000";

const CHART_CEJGM_CURVE_WIDTH = 3;
const CHART_CEJGM_CURVE_COLOR = "#0000CC";

const CHART_ROOT_CANAL_CURVE_WIDTH = 2.5;
const CHART_ROOT_CANAL_CURVE_COLOR = "#01579B";

const CHART_COMPACT_ZIGZAG_WIDTH = 2;
const CHART_COMPACT_ZIGZAG_COLOR = "#0000CC";

const CHART_CHIPPED_TOOTH_COLOR = "#0F0F0F";
const CHART_BRACE_TOOTH_COLOR = "#CC9900";

const TABLE_BOP_DOT_COLOR = "#FF0000";
const TABLE_PLAQUE_DOT_COLOR = "#0000FF";

const TABLE_NUMBER_COLOR_DEFAULT = "#000000";
const TABLE_NUMBER_COLOR_LARGE = "#FF0000";
// disable threshold
const TABLE_NUMBER_LARGE_THRESHOLD = 99;

const RECORD_FILE_NAME_DEFAULT = "Untitled";
