const TABLE_5_ID = "table_5";
const TABLE_5_TOOTH_NO = [43, 42, 41, 31, 32, 33];
const TABLE_5_IMAGE_CLIP = {"key": "mandible",
                            "start_x": 326,
                            "start_y": 42,
                            "width": 312,
                            "height": 416
                           };
const TABLE_5_CLICK_AREA = {"width" : [[16, 44, 16, 34, 16, 25, 16, 28, 16, 30, 16, 39, 16],
                                       [68, 50, 41, 44, 46, 63],
                                       [16, 40, 16, 29, 16, 29, 16, 27, 16, 29, 16, 46, 16],
                                       [16, 36, 16, 32, 16, 28, 16, 28, 16, 28, 16, 48, 16],
                                       [60, 48, 44, 44, 44, 72]],
                            "height": [64, 118, 69, 49, 116],
                            "usage": [[CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT],
                                      [CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS],
                                      [CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.FURCATION,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.FURCATION,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.FURCATION,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.FURCATION,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.FURCATION,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.FURCATION,
                                       CHART_CLICK_AREA_USAGE.COMPACT],
                                      [CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT],
                                      [CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS]]};
const TABLE_5_TOP_ROOT_CANAL_CURVE =
        [[[ROOT_CANAL_CURVE_SHAPE.REVERSE_C, 38, 72, 23, 164]],
         [[ROOT_CANAL_CURVE_SHAPE.REVERSE_C, 92, 71, 80, 147]],
         [[ROOT_CANAL_CURVE_SHAPE.ONE_ANCHOR, 135, 73, 128, 139, 137, 119]],
         [[ROOT_CANAL_CURVE_SHAPE.ONE_ANCHOR, 180, 75, 180, 138, 173, 129]],
         [[ROOT_CANAL_CURVE_SHAPE.ONE_ANCHOR, 222, 75, 231, 150, 215, 130]],
         [[ROOT_CANAL_CURVE_SHAPE.ONE_ANCHOR, 277, 70, 288, 169, 270, 141]]];
const TABLE_5_BOTTOM_ROOT_CANAL_CURVE =
        [[[ROOT_CANAL_CURVE_SHAPE.REVERSE_C, 29, 309, 17, 408]],
         [[ROOT_CANAL_CURVE_SHAPE.REVERSE_C, 83, 310, 73, 393]],
         [[ROOT_CANAL_CURVE_SHAPE.REVERSE_C, 130, 313, 117, 380]],
         [[ROOT_CANAL_CURVE_SHAPE.ONE_ANCHOR, 171, 310, 175, 381, 167, 357]],
         [[ROOT_CANAL_CURVE_SHAPE.ONE_ANCHOR, 214, 313, 224, 391, 206, 368]],
         [[ROOT_CANAL_CURVE_SHAPE.ONE_ANCHOR, 270, 312, 283, 411, 261, 380]]];
const TABLE_5_TOP_CHART_SETTING =
                        { "x_zero" : 3,
                          "y_zero" : 64,
                          "y_direction" : CHART_Y_DIRECTION.DOWN,
                          "x_grid" : [[ 13,  35,  60],
                                      [ 75,  89, 110],
                                      [121, 133, 150],
                                      [164, 178, 198],
                                      [208, 221, 244],
                                      [252, 276, 301]],
                          "y_base" :  [[64, 72, 64],
                                       [64, 72, 64],
                                       [64, 72, 64],
                                       [64, 72, 64],
                                       [64, 72, 64],
                                       [64, 72, 64]],
                          "grid_height" : 5.5,
                          "crown_pos": [[[36, 50]],
                                        [[89, 50]],
                                        [[134, 50]],
                                        [[179, 50]],
                                        [[220, 50]],
                                        [[272, 50]]],
                          "compact_pos": [[0, 35],
                                          [59, 33],
                                          [110, 33],
                                          [150, 33],
                                          [194, 33],
                                          [240, 33],
                                          [295, 35]],
                          "root_pos": [[[36, 87]],
                                       [[89, 87]],
                                       [[134, 87]],
                                       [[179, 87]],
                                       [[220, 87]],
                                       [[272, 87]]],
                          "tooth_no_pos" : [[25, 54],
                                            [81, 54],
                                            [126, 54],
                                            [170, 54],
                                            [214, 54],
                                            [266, 54]],
                          "root_canal_curve" : TABLE_5_TOP_ROOT_CANAL_CURVE};
const TABLE_5_MIDDLE_CHART_SETTING =
                        {"crown_pos":[[[36, 231]],
                                      [[89, 231]],
                                      [[134, 231]],
                                      [[179, 231]],
                                      [[220, 231]],
                                      [[272, 231]]],
                          "furcation_pos": [[22, 233],
                                            [75, 233],
                                            [120, 233],
                                            [162, 233],
                                            [210, 233],
                                            [257, 233]],
                          "furcation_type": FURCATION_GRADE_TYPE.SYMBOLS,
                          "compact_pos": [[0, 209],
                                          [55, 211],
                                          [100, 216],
                                          [145, 216],
                                          [188, 216],
                                          [233, 212],
                                          [295, 210]]};
const TABLE_5_BOTTOM_CHART_SETTING =
                        { "x_zero" : 3,
                          "y_zero" : 300,
                          "y_direction" : CHART_Y_DIRECTION.DOWN,
                          "x_grid" : [[  7,  25,  52],
                                      [ 63,  83,  99],
                                      [114, 133, 145],
                                      [157, 172, 190],
                                      [200, 216, 235],
                                      [246, 265, 301]],
                          "y_base" :  [[300, 312, 300],
                                       [300, 312, 300],
                                       [300, 312, 300],
                                       [300, 312, 300],
                                       [300, 312, 300],
                                       [300, 312, 300]],
                          "grid_height" : 5.5,
                          "crown_pos": [[[36, 284]],
                                        [[89, 284]],
                                        [[134, 284]],
                                        [[179, 284]],
                                        [[220, 284]],
                                        [[272, 284]]],
                          "root_pos": [[[36, 324]],
                                       [[89, 324]],
                                       [[134, 324]],
                                       [[179, 324]],
                                       [[220, 324]],
                                       [[272, 324]]],
                          "compact_pos": [[0, 272],
                                          [51, 269],
                                          [99, 269],
                                          [143, 269],
                                          [188, 269],
                                          [231, 269],
                                          [294, 274]],
                          "tooth_no_pos" : [[18, 291],
                                            [73, 291],
                                            [123, 291],
                                            [162, 291],
                                            [206, 291],
                                            [260, 291]],
                          "root_canal_curve" : TABLE_5_BOTTOM_ROOT_CANAL_CURVE};
