const TABLE_2_ID = "table_2";
const TABLE_2_TOOTH_NO = [13, 12, 11, 21, 22, 23];
const TABLE_2_IMAGE_CLIP = {"key": "palate",
                            "start_x": 304,
                            "start_y": 23,
                            "width": 320,
                            "height": 415
                           };
const TABLE_2_CLICK_AREA = {"width": [[65, 44, 58, 61, 40, 52],
                                      [16, 41, 16, 28, 16, 42, 16, 45, 16, 24, 16, 28, 16],
                                      [16, 32, 16, 31, 16, 44, 16, 43, 16, 30, 16, 28, 16],
                                      [59, 41, 58, 59, 43, 60],
                                      [16, 35, 16, 25, 16, 42, 16, 43, 16, 27, 16, 36, 16]],
                            "height": [126, 53, 67, 107, 62],
                            "usage": [[CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS],
                                      [CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT],
                                      [CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.FURCATION,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.FURCATION,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.FURCATION,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.FURCATION,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.FURCATION,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.FURCATION,
                                       CHART_CLICK_AREA_USAGE.COMPACT],
                                      [CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS,
                                       CHART_CLICK_AREA_USAGE.CLASS],
                                      [CHART_CLICK_AREA_USAGE.NONE,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT,
                                       CHART_CLICK_AREA_USAGE.NO,
                                       CHART_CLICK_AREA_USAGE.COMPACT]]};
const TABLE_2_TOP_ROOT_CANAL_CURVE =
        [[[ROOT_CANAL_CURVE_SHAPE.REVERSE_C, 40, 105, 42, 11]],
         [[ROOT_CANAL_CURVE_SHAPE.REVERSE_C, 88, 110, 81, 40]],
         [[ROOT_CANAL_CURVE_SHAPE.REVERSE_C, 137, 102, 135, 34]],
         [[ROOT_CANAL_CURVE_SHAPE.C, 197, 104, 202, 36]],
         [[ROOT_CANAL_CURVE_SHAPE.C, 246, 113, 254, 39]],
         [[ROOT_CANAL_CURVE_SHAPE.C, 293, 110, 299, 20]]];
const TABLE_2_BOTTOM_ROOT_CANAL_CURVE =
        [[[ROOT_CANAL_CURVE_SHAPE.REVERSE_C, 36, 338, 26, 250]],
         [[ROOT_CANAL_CURVE_SHAPE.REVERSE_C, 80, 345, 72, 273]],
         [[ROOT_CANAL_CURVE_SHAPE.REVERSE_C, 129, 339, 123, 267]],
         [[ROOT_CANAL_CURVE_SHAPE.C, 187, 339, 194, 265]],
         [[ROOT_CANAL_CURVE_SHAPE.ONE_ANCHOR, 241, 344, 249, 271, 239, 288]],
         [[ROOT_CANAL_CURVE_SHAPE.C, 283, 341, 292, 250]]];
const TABLE_2_TOP_CHART_SETTING =
                        { "x_zero" : 3,
                          "y_zero" : 126,
                          "y_direction" : CHART_Y_DIRECTION.UP,
                          "x_grid" : [[ 23,  40,  59],
                                      [ 74,  86, 103],
                                      [116, 138, 161],
                                      [174, 198, 218],
                                      [231, 246, 260],
                                      [273, 292, 313]],
                          "y_base" :  [[126, 105, 126],
                                       [126, 115, 126],
                                       [126, 105, 126],
                                       [126, 105, 126],
                                       [126, 115, 126],
                                       [126, 115, 126]],
                          "grid_height" : 5.5,
                          "crown_pos": [[[41, 142]],
                                        [[88, 142]],
                                        [[137, 142]],
                                        [[196, 142]],
                                        [[249, 142]],
                                        [[293, 142]]],
                          "root_pos": [[[41, 84]],
                                       [[88, 84]],
                                       [[137, 84]],
                                       [[196, 84]],
                                       [[249, 84]],
                                       [[293, 84]]],
                          "compact_pos": [[0, 133],
                                          [58, 133],
                                          [102, 133],
                                          [160, 133],
                                          [221, 133],
                                          [261, 133],
                                          [305, 133]],
                          "tooth_no_pos" : [[30, 148],
                                            [76, 148],
                                            [128, 148],
                                            [188, 148],
                                            [236, 148],
                                            [282, 148]],
                          "root_canal_curve" : TABLE_2_TOP_ROOT_CANAL_CURVE};
const TABLE_2_MIDDLE_CHART_SETTING =
                        {"crown_pos":[[[29, 211]],
                                      [[77, 211]],
                                      [[133, 211]],
                                      [[194, 211]],
                                      [[239, 211]],
                                      [[290, 211]]],
                          "furcation_pos": [[22, 219],
                                            [69, 219],
                                            [120, 219],
                                            [181, 219],
                                            [236, 219],
                                            [280, 219]],
                          "furcation_type": FURCATION_GRADE_TYPE.SYMBOLS,
                          "compact_pos": [[0, 205],
                                          [49, 199],
                                          [96, 199],
                                          [156, 199],
                                          [215, 199],
                                          [261, 203],
                                          [305, 205]]};
const TABLE_2_BOTTOM_CHART_SETTING =
                        { "x_zero" : 3,
                          "y_zero" : 353,
                          "y_direction" : CHART_Y_DIRECTION.UP,
                          "x_grid" : [[ 13,  35,  51],
                                      [ 65,  79,  94],
                                      [105, 124, 154],
                                      [167, 190, 206],
                                      [226, 241, 255],
                                      [267, 283, 302]],
                          "y_base" :  [[353, 342, 353],
                                       [353, 347, 353],
                                       [353, 342, 353],
                                       [353, 342, 353],
                                       [353, 347, 353],
                                       [353, 342, 353]],
                          "grid_height" : 5.5,
                          "crown_pos": [[[31, 372]],
                                        [[77, 372]],
                                        [[128, 372]],
                                        [[187, 372]],
                                        [[241, 372]],
                                        [[284, 372]]],
                          "root_pos": [[[31, 320]],
                                       [[77, 320]],
                                       [[128, 320]],
                                       [[187, 320]],
                                       [[241, 320]],
                                       [[284, 320]]],
                          "compact_pos": [[0, 362],
                                          [52, 362],
                                          [92, 362],
                                          [152, 362],
                                          [210, 362],
                                          [253, 362],
                                          [305, 362]],
                          "tooth_no_pos" : [[25, 375],
                                            [69, 375],
                                            [114, 375],
                                            [180, 375],
                                            [231, 375],
                                            [273, 375]],
                          "root_canal_curve" : TABLE_2_BOTTOM_ROOT_CANAL_CURVE};
